version: "3.9"

services:
  prometheus:
    container_name: shortener-prometheus
    image: prom/prometheus:v2.45.0
    build:
      context: prometheus
      dockerfile: Dockerfile
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web-config.yml"
    ports:
      - "9093:9090"
    volumes:
      - ../../persistentdata/prometheus/data:/prometheus
    user: root


  grafana:
    container_name: shortener-grafana
    image: grafana/grafana:9.5.8-ubuntu
    ports:
      - "3003:3000"
    volumes:
      - ../../persistentdata/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/)'
