global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: shortener_api
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: metrics
    static_configs:
      - targets: ['localhost:9090']
