"""14082023 add doc for column

Revision ID: 103570128e2a
Revises: 7ca617416380
Create Date: 2023-08-14 16:21:13.138279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103570128e2a'
down_revision = '7ca617416380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
