"""feat: DB creation

Revision ID: 678b744b6980
Revises: 
Create Date: 2023-08-04 21:27:42.659372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678b744b6980'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
