"""feat: DB creation2

Revision ID: 73c679aed5d9
Revises: c6c88a399a51
Create Date: 2023-08-04 16:56:56.254574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c679aed5d9'
down_revision = 'c6c88a399a51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
