"""feat: DB creation

Revision ID: c6c88a399a51
Revises: 
Create Date: 2023-08-04 16:52:58.182982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c88a399a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('clicks_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_key'), 'url', ['key'], unique=True)
    op.create_index(op.f('ix_url_secret_key'), 'url', ['secret_key'], unique=True)
    op.create_index(op.f('ix_url_target_url'), 'url', ['target_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_target_url'), table_name='url')
    op.drop_index(op.f('ix_url_secret_key'), table_name='url')
    op.drop_index(op.f('ix_url_key'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
