version: 1
disable_existing_loggers: false


formatters:
  json:
    "()": "pythonjsonlogger.jsonlogger.JsonFormatter"
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"

  my_stdout:
    format: "%(asctime)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"

  docker_format:
    format: "%(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: docker_format

  my_null:
    class: logging.NullHandler


loggers:

  app.api:
    handlers:
      - console
    level: INFO
    propagate: false

  app.service_layer:
    handlers:
      - console
    level: DEBUG
    propagate: false

  uvicorn.access:
    handlers:
      - console
    level: INFO
    propagate: false

  uvicorn.error:
    handlers:
      - console
    level: INFO
    propagate: false

  sqlalchemy:
    handlers:
      - console
    level: INFO
    propagate: false

  sqlalchemy.engine.Engine:
    handlers:
      - console
    level: INFO
    propagate: false

  sqlalchemy.orm.mapper:
    handlers:
      - my_null
    propagate: false
